use dataWarehouse
/*
  Magnitude Analysis : Compare the measure values by the categories.
*/

-- Task : Find the total number of customers by countries

SELECT
 country,
 COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-----------------------------------------------------------------------------------------------------
-- Task : Find the total number of customers by gender

SELECT
 gender,
 COUNT(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;;

-----------------------------------------------------------------------------------------------------
-- Task : Find the total number of product by category

SELECT
 category,
 COUNT(product_key) as total_products
FROM gold.dim_product
GROUP BY category
ORDER BY total_products DESC;
-----------------------------------------------------------------------------------------------------
-- Task : What is the average cost in each category

SELECT
 category,
 AVG(product_cost) as average_cost
FROM gold.dim_product
GROUP BY category
ORDER BY average_cost DESC;
-----------------------------------------------------------------------------------------------------
-- Task : What is the total revenue generated for each category
-- NOTE use FACT table on start AS LEFT table then join on DIM
SELECT
  b.category,
  SUM(a.sales_amount) as revenue_category
FROM gold.fact_sales AS a 
LEFT JOIN gold.dim_product AS b
ON a.product_key = b.product_key
GROUP BY b.category
ORDER BY revenue_category DESC;
-----------------------------------------------------------------------------------------------------
-- Task : What is the total revenue generated by each customer

SELECT
  b.customer_key,
  b.firstname + ' ' + b.lastname AS customer_name,
  SUM(a.sales_amount) as revenue_customer
FROM gold.fact_sales AS a
LEFT JOIN  gold.dim_customers  AS b
ON a.customer_key = b.customer_key
GROUP BY b.customer_key, b.firstname, b.lastname
ORDER BY revenue_customer DESC;
-----------------------------------------------------------------------------------------------------
-- Task : What is the destribution of sold items across countries
SELECT
 b.country,
 SUM(a.quantity) as total_sold
FROM gold.fact_sales AS a
JOIN gold.dim_customers AS b
ON a.customer_key = b.customer_key
GROUP BY b.country
ORDER BY total_sold DESC;
-----------------------------------------------------------------------------------------------------
-- LOW CARDINALITY DIMENSION : Dimension with few unique values.
--                             e.g. Category, Country, Gender....
---------------------------------------------------------------------
-- HIGH CARDINALITY DIMENSION : Dimension with large number of unique values.
--                             e.g. Product, Costomer, Address....
-----------------------------------------------------------------------------------------------------